### ISSUE TITLE
CosmosDB to CosmosDB  doesn't migrate "Id" field

### ISSUE THREAD

**Issue by vacuum-in** [AzureCosmosDB/data-migration-desktop-tool#100]
At the source database we have two fields "Id" and "id" where "id" is the CosmosDB standard field. Only standard field is created at sink container.
Source container:
```
{
    "Id": "f703df15-32fa-4788-d7cd-08dbf7edaaaa",
.....
    "id": "f703df15-32fa-4788-d7cd-08dbf7edaaaa"
}
```
Sink container:
```
{
.....
    "id": "f703df15-32fa-4788-d7cd-08dbf7edaaaa"
...
}
```

"IncludeMetadataFields" set to true

**Comment by sebas-ambrero** [comment]
@vacuum-in I had the same issue with dmt-2.1.4-win-x64. 

Checked out the code, and ran it locally, that worked fine for me.

**Comment by adambarath** [comment]
Any update on this?

**Comment by bowencode** [comment]
Using the latest code, the `PreserveMixedCaseIds` sink setting will now update this behavior to include multiple cases of id fields.
