### ISSUE TITLE
$type property of document not being copied from or to Cosmos

### ISSUE THREAD

**Issue by JohnDStrasz** [AzureCosmosDB/data-migration-desktop-tool#120]
When using the tool to backup from Cosmos DB either directory to another Cosmos DB or JSON files, there are $type properties in our documents that are not being copied. We're using the IncludeMetadataFields setting in both the Source and Sink settings.

"itemType": {
        "$type": "xyz123",                                  <<<<<<<<<<<<
        "property1": false,
        "property2": false
        "value": 3,
        "displayName": "ABC"
    },

**Comment by crpietschmann** [comment]
This is related to Issue #97
