### ISSUE TITLE
Unable to Connect Azure Cosmos MongoDB with Navicat Program

### ISSUE THREAD

**Issue by loyal812** [AzureCosmosDB/data-migration-desktop-tool#124]
📝 **Issue Description:**
I am trying to connect Azure Cosmos MongoDB to my local machine using Navicat program. However, I am facing issues with the connection. Could someone please provide guidance or a solution on how to establish a successful connection between Azure Cosmos MongoDB and Navicat?

Thank you in advance for your help!

**Comment by bowencode** [comment]
I would recommend that you contact support for the program you are trying to use which is unrelated to this tool but in general a connection string that is provided by Azure is used to connect to Cosmos DB.
