### ISSUE TITLE
Capabilities are unclear

### ISSUE THREAD

**Issue by alekseys** [AzureCosmosDB/data-migration-desktop-tool#32]
It's not clear what actual sources/targets this tools supports. Simply saying "Mongo" doesn't cut it (what version/editions of MongoDB? For example, is Cosmos DB for MongoDB supported as a source/target?). Moreover, it's not clear what it's actually capable of migrating, just data or indexes as well? What happens if some data or indexes aren't supported by the target (e.g. document is larger than the limit, indexes on nested paths, etc.)?

**Comment by markjbrown** [comment]
Hi Aleksey.

The mongo server-version is dependent on the .NET driver version. The driver can be mapped to the supported server versions which are available here, https://www.mongodb.com/docs/drivers/csharp/current/compatibility/#std-label-csharp-compatibility-tables

As for indexes, etc. created, these are whatever are the defaults when creating a new collection.

Thanks.

**Comment by seesharprun** [comment]
@markjbrown, would this type of table help in the documentation?

| Extension | Source | Sink |
| --- | --- | --- |
| MongoDB<sup>1</sup> |  ✅ | ✅ |
| JSON |  ✅ | ✅ |

> <sup>1</sup> MongoDB version 3.6 or later supported.
