### ISSUE TITLE
Azure Cosmos DB Source Date Format Issues

### ISSUE THREAD

**Issue by RichMercer** [AzureCosmosDB/data-migration-desktop-tool#36]
I have a document stored in Cosmos DB with a date value stored as ISO-8601 as follows:

```
{
"id": "ac32038ead44b2a3ece6d57eef8a81"
"dateCreated": "2021-04-22T16:24:40.739451Z"
}
```

When exporting the document and saving to JSON it's saved as follows:

```
{
"id": "ac32038ead44b2a3ece6d57eef8a81",
"dateCreated": "22/04/2021 16:24:40",
}
```

When importing the JSON back into Cosmos DB it's causing issues due to not matching the expected date format. I expect the export to store DateTime in the same ISO-8601 format as the source and not cause a conversion. The converted format is also fragile as it's dependant on the machine culture settings with regard to date parsing.

**Comment by bowencode** [comment]
Included in [Release v2.0.3](https://github.com/AzureCosmosDB/data-migration-desktop-tool/releases/tag/v2.0.3)
