### ISSUE TITLE
Documenting some behaviors

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/data-migration-desktop-tool#41]
Can you document some additional things?

1. Acceptable values for ConnectionMode. Gateway is used in the sample. Not clear if the other is Direct or Direct-TCP, etc.

1. When I run this with the source and sink settings filled in at the top and also using operations, it skips over the first set of source and sink settings. I don't think this was clear in the NoSQL docs.

1. Can you provide more examples of what the migrationsettings.json might look like? I think this would be helpful for users to quickly adapt to their data moving.

thanks!

**Comment by bowencode** [comment]
Docs updated for [Cosmos-NoSql](https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/main/Extensions/Cosmos/README.md), [MigrationSettings](https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/main/ExampleConfigs.md), and [Operations](https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/main/README.md)
