### ISSUE TITLE
Missing Releases folder...

### ISSUE THREAD

**Issue by br14** [AzureCosmosDB/data-migration-desktop-tool#43]
"To use the tool, download the latest zip file for your platform (win-x64, mac-x64, or linux-x64) from [Releases](https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/main/releases)"

Sadly the releases folder doesn't exist.

![image](https://user-images.githubusercontent.com/418641/233409720-93fe9212-7f6f-426a-b122-1a858914b132.png)

**Comment by bowencode** [comment]
Link fixed in docs
