### ISSUE TITLE
Nested arrays are not supported with Cosmos SQL Sink

### ISSUE THREAD

**Issue by RemyBoyer** [AzureCosmosDB/data-migration-desktop-tool#64]
Hello,

Considering a document that looks like this from Cosmos SQL:

```json
{
  "array": [
    [
      {
        "id": "sub1"
      },
      {
        "id": "sub2"
      }
    ]
  ]
}
```

When using the cosmos SQL sink, the document is written this way:

```json
{
  "array": [
    [
      {
        "Items": {
          "id": "sub1"
        }
      },
      {
        "Items": {
          "id": "sub2"
        }
      }
    ]
  ]
}
```

The extra "Items" property is actually a raw serialization of a `CosmosDictionaryDataItem`.

I've managed to fix the issue on `CosmosDataSinkExtension`, and am providing a PR, but the issue may actually be more global.

**Comment by bowencode** [comment]
Thanks @RemyBoyer for this fix! It will go out in the next release and will also be added to the MongoDB extension to allow it to support nesting.
