### ISSUE TITLE
Number converting issue

### ISSUE THREAD

**Issue by MarioGit1** [AzureCosmosDB/data-migration-desktop-tool#71]
I am facing an issue with a data structure that includes a zip code:
If I set "Cosmos-nosql" as the data source and "json" as the destination, the zip code is correctly generated in the resulting text file. However, if I reverse the setup by using the JSON file as the source and "Cosmos-nosql" as the destination, the zip code is saved as a floating-point number instead. I expect the zip code to remain consistent regardless of the data flow direction.

Before:
{
....
"zip": 3456
...
}

in json file as sink:
{
....
"zip": 3456
...
}

in cosmosDB after importing:
{
....
"zip": 3456.0
...
}

Is there any way to get the zip code as expected without converting it to a string.

Thanks.

**Comment by bowencode** [comment]
Are you seeing somewhere that the values 3456 != 3456.0? Cosmos DB uses JSON spec for numbers, which don't differentiate integer and floating point types. When you say "in cosmosDB", the actual value stored for 3456.0 and 3456 should be the same, but depending on what is being used to view the value the formatting of that same number can be different.

With seemingly identical data values if they're coming out differently from the same formatter I'm wondering if there is actually a difference that's being hidden by the formatter, something like a tiny rounded off difference resulting from a type conversion somewhere along the way.

**Comment by MarioGit1** [comment]
Thanks for quick answering. You are correct, in JSON there is no distinction between floating point and integer values. We have a dotnet7.0 application that is connected to our cosmosDB. Our model contains both doubles and integers. As the serializer, we utilize System.Text.Json, which throws an exception if the number is 1.0 and the type is an integer. Although this topic is unrelated to the migration tool, it is essential for the tool to produce consistent results regardless of the direction and format, so we don't need to concern ourselves with data types. In the cosmosDB data explorer, the difference is not visible (it displays '1,' but internally it is evidently '1.0'). I'm uncertain if this is a genuine problem with the migration tool, but our expectation was that the source and the destination would always be identical.
