### ISSUE TITLE
Cannot use Azure Cosmos DB as source: Request is made with a forbidden encryption

### ISSUE THREAD

**Issue by tjkb** [AzureCosmosDB/data-migration-desktop-tool#79]
Repro steps:
1. create new Azure Cosmos DB
2. copy connection string
3. in the tool, choose Cosmos as source and paste the connection string
4. append ;Database=databasename
5. Click verify

Then, the following message appears:
![image](https://github.com/AzureCosmosDB/data-migration-desktop-tool/assets/40162050/10e79f18-cf2c-4ca1-a539-45c0bac52977)

Expected outcome would be that the connection string is successfully verified. The tool works for old Azure Cosmos DB instances. But not for a newly generated one.

I'm using version 1.8.3

**Comment by bowencode** [comment]
Have you compared the minimum TLS version settings on the failing vs working instances? In the Azure portal you should be able to find it under Settings->Networking->Connectivity. Including Database in the connection string shouldn't change the TLS functionality but if an older version is being used, that setting on the individual instances could cause different behavior.
