### ISSUE TITLE
Error: System.ArgumentException: The connection string is missing a required property: AccountEndpoint

### ISSUE THREAD

**Issue by uluhonolulu** [AzureCosmosDB/data-migration-desktop-tool#88]
I'm using `"Source": "cosmos-nosql"` in my settings file.

My CosmosDB connection string (copied from the portal) has the usual MongoDB format: `mongodb://<accoint name>:<bunch of stuff>@<accoint name>.mongo.cosmos.azure.com:10255/<bunch or query params>`.

Apparently, dmt doesn't like this format and throws an exception.

Where do I get the dmt-friendly connection string? All the tutorials that I found display a screenshot with the expected format. Am I the only one with a different connection string?

**Comment by bowencode** [comment]
If you're using a Cosmos account with the Mongo API you should use the Mongo Extension that you can find settings for here: https://github.com/AzureCosmosDB/data-migration-desktop-tool/tree/main/Extensions/Mongo

The Cosmos-NoSQL extension is only for the default "API for NoSQL" type of account.
