### ISSUE TITLE
System.AggregateException: Configuration for CosmosSourceSettings is invalid (ConnectionString must be specified unless UseRbacAuth is true)

### ISSUE THREAD

**Issue by dhapagopal1** [AzureCosmosDB/data-migration-desktop-tool#98]
Hi Team,

When i used this migration tool after run dmt command given below error.
ConnectionString must be specified unless UseRbacAuth is true
System.AggregateException: Configuration for CosmosSourceSettings is invalid (ConnectionString must be specified unless UseRbacAuth is true)

Thank's
Gopal

**Comment by bowencode** [comment]
As the error states, ConnectionString is a required setting for the extension you're using. Refer to extension documentation for required and optional settings: https://github.com/AzureCosmosDB/data-migration-desktop-tool#extension-documentation
