### ISSUE TITLE
Can I include InternalFields and Prettify the JSON output like the *other* tool did?

### ISSUE THREAD

**Issue by jasonnaylor-tester** [AzureCosmosDB/data-migration-desktop-tool#99]
The other (old/previous/deprecated) azure-documentdb-datamigrationtool had a couple of fields for prettifying the output and including the internal fields:

/t.Prettify:true  
/s.InternalFields:true

I can't seem to find anything similar in the syntax or migrationsettings.json - am I missing something, or are these options not available in this tool?

**Comment by jasonnaylor-tester** [comment]
I found the answer to one of my queries: you can use the IncludeMetadataFields flag for the internalFields:

"IncludeMetadataFields": true,

**Comment by bowencode** [comment]
The JSON extension includes an "Indented" option for formatting as indented and multi-line. This should be included in the SinkSettings.

https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/main/Extensions/Json/README.md#sink
